version: "3"

services:
  #  ecs:
  #    build: ./ecs
  #  nginx:
  #    build: ./nginx
  #    ports:
  #      - 8080:8080
#  ilias:
#    build: ./ilias
#    ports:
#      - 8082:80
  websocket-api:
    build: ./websocket-api
    ports:
      - 8083:8080
    environment:
      JWKS_FILE: /config/jwks.json
    volumes:
      - ./jwks.json:/config/jwks.json:ro
  activemq:
    image: viplab-artemis:2.11.0
    build: 
      context: ./artemis
      args:
        ACTIVEMQ_ARTEMIS_VERSION: "2.11.0"
    ports:
      - 8084:8161
    environment:
      ARTEMIS_USERNAME: user
      ARTEMIS_PASSWORD: password
  standalone-frontend:
    image: viplab/standalone-frontend:latest
    ports:
      - 8085:5000
    volumes:
      - ./jwks.private.json:/jwks.private.json:ro
      - ./examples:/input:ro
