version: '3'

services:
  ecs:
    build: ./ecs
    ports:
      - 8080:80
#  backend:
#    build: 
#      context: ./backend
#      args:
#        GITHUB_TOKEN:
  ilias:
    build: ./ilias
    ports:
      - 80:80
