version: '3'

services:
  ecs:
    build: ./ecs
  nginx:
    build: ./nginx
    ports:
      - 8080:8080
#  backend:
#    build: 
#      context: ./backend
#      args:
#        GITHUB_TOKEN:
  ilias:
    build: ./ilias
    ports:
      - 8082:80
