version: '3'

services:
  ecs:
    build: ./ecs
  nginx:
    build: ./nginx
    ports:
      - 8080:8080
#  backend:
#    build:
#      context: ./backend
#      args:
#        GITHUB_TOKEN:
  ilias:
    build: ./ilias
    ports:
      - 8082:80
  websocket-api:
    image: websocket-api
    ports:
      - 8083:9080
    env_file: websocket-api/websocket-api-config.env
    volumes:
      - ./jwks.json:/config/jwks.json:ro
  activemq:
    image: vromero/activemq-artemis:2.11.0
    ports:
      - 8084:8161
    environment:
      ARTEMIS_USERNAME: user
      ARTEMIS_PASSWORD: password
