# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# ActiveMQ Artemis

FROM openjdk:8 as builder
LABEL maintainer="Per Pascal Seeland <pascal.seeland@tik.uni-stuttgart.de"
# Make sure pipes are considered to determine success, see: https://github.com/hadolint/hadolint/wiki/DL4006
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
WORKDIR /opt

ARG ACTIVEMQ_ARTEMIS_VERSION

ENV ARTEMIS_USER artemis
ENV ARTEMIS_PASSWORD artemis
ENV ANONYMOUS_LOGIN false
ENV CREATE_ARGUMENTS --user ${ARTEMIS_USER} --password ${ARTEMIS_PASSWORD} --silent --http-host 0.0.0.0 --relax-jolokia

# add user and group for artemis
RUN groupadd -g 1000 -r artemis && useradd -r -u 1000 -g artemis artemis \
 && apt-get -qq -o=Dpkg::Use-Pty=0 update && \
    apt-get -qq -o=Dpkg::Use-Pty=0 install -y --no-install-recommends \
    libaio1 wget && \
    rm -rf /var/lib/apt/lists/*

USER root

RUN mkdir /var/lib/artemis && chown -R artemis.artemis /var/lib/artemis
RUN  wget "https://repository.apache.org/content/repositories/releases/org/apache/activemq/apache-artemis/${ACTIVEMQ_ARTEMIS_VERSION}/apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}-bin.tar.gz" && \
     wget "https://repository.apache.org/content/repositories/releases/org/apache/activemq/apache-artemis/${ACTIVEMQ_ARTEMIS_VERSION}/apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}-bin.tar.gz.asc" && \
     wget "http://apache.org/dist/activemq/KEYS" && \
     gpg --no-tty --import "KEYS" && \
     gpg --no-tty "apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}-bin.tar.gz.asc" && \
     tar xfz "apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}-bin.tar.gz" && \
     ln -s "/opt/apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}" "/opt/apache-artemis" && \
     rm -f "apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}-bin.tar.gz" "KEYS" "apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}-bin.tar.gz.asc"; 

RUN rm -r  /opt/apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}/web/{api,examples,user-manual,hacking-guide,migration-guide} && rm -r  /opt/apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}/examples

USER artemis
WORKDIR /var/lib/artemis

RUN /opt/apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}/bin/artemis create ${CREATE_ARGUMENTS} .


FROM adoptopenjdk/openjdk8:jre8u242-b08-alpine
LABEL maintainer="Pascal Seeland <pascal.seeland@tik.uni-stuttgart.de>"
ARG ACTIVEMQ_ARTEMIS_VERSION
ENV ACTIVEMQ_ARTEMIS_VERSION=$ACTIVEMQ_ARTEMIS_VERSION

# add user and group for artemis
RUN addgroup -g 1000 -S artemis && adduser -u 1000 -S -G artemis artemis

# Sadly this line is likely to fail every so often, see: https://medium.com/@stschindler/the-problem-with-docker-and-alpines-package-pinning-18346593e891
# Still versions are pinned to maintain some small level of https://reproducible-builds.org/
RUN apk add --no-cache \
  libaio=0.3.112-r1

RUN mkdir /var/lib/artemis && chown -R artemis.artemis /var/lib/artemis
USER artemis
COPY --from=builder "/opt/apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}" "/opt/apache-artemis-${ACTIVEMQ_ARTEMIS_VERSION}"
COPY --from=builder "/var/lib/artemis" "/var/lib/artemis"
#COPY --from=builder "/opt/jmx-exporter" "/opt/jmx-exporter"

# Web Server
EXPOSE 8161 \
# JMX Exporter
    9404 \
# Port for AMQP
    5672

WORKDIR /var/lib/artemis

COPY broker.xml etc
COPY docker-run.sh /

USER artemis

# Expose some outstanding folders
VOLUME ["/var/lib/artemis"]
WORKDIR /var/lib/artemis

ENTRYPOINT ["bin/artemis"]
CMD ["run"]
